name: Run Tmate Script on SUSE (Zypper)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-tmate:
    runs-on: [self-hosted, suse]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Tmate Script
        run: python3 Tmate.py
